[package]
name = "ucloud-cdn-log-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
csv = "1"

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1
panic = 'abort'